[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Needed for dotrain compose
ffi = true

solc = "0.8.19"
optimizer = true
optimizer_runs = 100000

bytecode_hash = "none"
cbor_metadata = false

# Build metadata used for testing rain meta aware contracts in this folder rather
# than expose ffi to forge.
fs_permissions = [
  { access = "read", path = "out/reference/UniswapV2LibraryConcrete.sol/UniswapV2LibraryConcrete.json" },
  { access = "read", path = "out/quoter/Quoter.sol/Quoter.json" },
  { access = "read", path = "./lib/rain.orderbook/lib/rain.interpreter/meta/RainterpreterExpressionDeployerNPE2.rain.meta"},
  { access = "read-write", path = "test/csvs"}
]

remappings = [
  "rain.interpreter/=lib/rain.orderbook/lib/rain.interpreter/src",
  "rain.metadata/=lib/rain.orderbook/lib/rain.metadata/src"
]


[fuzz]
runs = 1024

[profile.reference]

solc = "0.6.6"
src = "reference/src"
test = 'reference/test'
script = 'reference/script'
out = "out/reference/"
libs = ["reference/lib"]
remappings = [
    "v2-core/=reference/lib/v2-core/",
    "v2-periphery/=reference/lib/v2-periphery/",
    "@uniswap/v2-core/=reference/lib/v2-core/",
    "@uniswap/v2-periphery/=reference/lib/v2-periphery/"
]

[profile.quoter]

solc = "0.7.6"
src = "lib/view-quoter-v3/contracts"
test = "lib/view-quoter-v3/test"
script = "lib/view-quoter-v3/script"
out = "out/quoter/"
libs = ["lib/view-quoter-v3/lib"]
remappings = [
    "v3-periphery/=lib/view-quoter-v3/lib/v3-periphery/",
]