name: Rainix CI
on: [push]

jobs:
  standard-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    env:
      RPC_URL_ETH: ${{ secrets. RPC_URL_ETH}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop --command uniswap-prelude
      - run: nix develop --command rainix-sol-prelude
      - run: nix develop --command i9r-prelude
        working-directory: lib/rain.orderbook/lib/rain.interpreter
      - run: mkdir -p test/csvs
      - run: nix develop --command rainix-sol-test
